### ISSUE TITLE
Is this a template or a lib?

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-web#1]
From setup.ts , seems this is a template for user to fork and use directly. So setup.ts helps user setup MongoDB account.

**Comment by ralphhanna** [comment]
This is a template, a demo for developers to start with and should be customized to meet specific needs
1. Edit .env 
2. Edit WorkflowApp/configuration.ts/js to apply other implementation like SQL drivers instead of MongoDB
3. Edit WorkflowApp/appServices.ts/js to handle Service Tasks required for the application
4. Edit WorkflowApp/appUtils.ts/js to handle various Scripts 
5. Edit userAccess library to meet specific application need for authentication and email
6. Edit Views/Routers to meet UI changes
